### ISSUE TITLE
Adding html-webpack-plugin for auto generated index.html file

### ISSUE THREAD

**Issue by nanomosfet** [jhuynh85/react-scss-webpack-boilerplate#1]
Adding that plugin to your html file will allow you to ignore the `dist` file completely and include your html file in your build. 

check out https://github.com/nanomosfet/custom-portfolio/blob/master/webpack.common.js

I can open a PR for this if you want. 

some guide on how to do it: https://webpack.js.org/concepts/plugins/

**Comment by jhuynh85** [comment]
Just added it in c582d36509dfbfcd12cd7b221f4189e53dea4c20, thanks!
